--liquibase formatted sql

--changeset trinhvo:1
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_email VARCHAR2(255),
    total_amount NUMBER(19, 2),
    status VARCHAR2(50)
);
--rollback DROP TABLE orders;

--changeset trinhvo:2
CREATE TABLE outbox (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR2(255) NOT NULL,
    aggregate_id VARCHAR2(255) NOT NULL,
    type VARCHAR2(255) NOT NULL,
    payload CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--rollback DROP TABLE outbox;
